language: java
jdk: oraclejdk8
services:
- docker
deploy:
  provider: gae
  keyfile: client-secret.json
  project: workshop-deploy-microservice
before_install:
- openssl aes-256-cbc -K $encrypted_e49c2607727b_key -iv $encrypted_e49c2607727b_iv
  -in client-secret.json.enc -out client-secret.json -d
- docker login -u mickey0142 -p mickey_15
    && docker build -t mickey0142/catalog_service ./
    && docker push mickey0142/catalog_service
    && docker build -t mickey0142/product_service ./
    && docker push mickey0142/product_service
notifications:
  email: false
