language: java
jdk: oraclejdk8
services:
  - docker
before_install:
- openssl aes-256-cbc -K $encrypted_45d1b36fa803_key -iv $encrypted_45d1b36fa803_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
# If the SDK is not already cached, download it and unpack it
- tar -xzf credentials.tar.gz
- mkdir -p lib
deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "workshop-deploy-microservice"
