language: java
jdk: oraclejdk8
services:
  - docker
before_install:
  - DECRYPT_COMMAND
  - openssl aes-256-cbc -K $encrypted_e49c2607727b_key -iv $encrypted_e49c2607727b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "workshop-deploy-microservice"
